config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :cars do
    resource :like, module: :cars

    member do
      post 'favorite'
      delete 'unfavorite'
    end

    collection do
      get 'search'
      get 'my_search'
      get 'liked_search'
      get 'favorite_search' 
      get 'collection', to: 'cars#collection'
      get 'my_cars', to: 'cars#my_cars'
      get 'liked_cars', to: 'cars#liked_cars'
      get 'favorite_cars', to: 'cars#favorite_cars'
      get 'models'
    end
  end

  root 'home#index'
  get 'collection', to: 'home#collection'
  get 'account', to: 'home#account'
  get 'about', to: 'home#about'

  get "up" => "rails/health#show", as: :rails_health_check
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorited_by_users, through: :favorites, source: :user
  belongs_to :user
  has_many :likes, as: :record
  has_one_attached :image

  before_save :format_brand

  def liked_by?(user)
    likes.where(user: user).any?
  end

  def like(user)
    likes.where(user: user).first_or_create
  end

  def unlike(user)
    likes.where(user: user).destroy_all
  end

  validates :brand, presence: true
  validates :image, presence: { message: 'must be attached' }

  private

  def format_brand
    self.brand = brand.downcase.capitalize
  end 

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :car

  validates :user_id, uniqueness: { scope: :car_id, message: "You can only favorite a car once" }
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :record, polymorphic: true, counter_cache: true

  validates :user_id, uniqueness: { scope: :record_id }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :favorites, dependent: :destroy
  has_many :favorite_cars, through: :favorites, source: :car
  has_many :likes
  has_many :cars
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cars/likes_controller.rb
class Cars::LikesController < ApplicationController
    include ActionView::RecordIdentifier
  
    before_action :authenticate_user!
    before_action :set_car
  
    def update
      if @car.liked_by?(current_user)
        @car.unlike(current_user)
      else
        @car.like(current_user)
      end 
    
    respond_to do |format|
        format.turbo_stream
        format.html { redirect_to request.referer || root_path }
      end
    end
  
    private
  
    def set_car
      @car = Car.find(params[:car_id])
    end
  end
  

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show, :search]
  before_action :set_car, only: %i[show edit update destroy]
  before_action :authorize_user!, only: [:edit, :update, :destroy]
  before_action :load_makes, only: %i[new create edit update]

  # GET /cars or /cars.json
  def index
    @cars = Car.order(created_at: :desc)
  end

  def my_cars
    @cars = Car.where(user_id: current_user.id).order(created_at: :desc)
  end

  def liked_cars
    @cars = Car.joins(:likes).where(likes: { user_id: current_user.id }).order(created_at: :desc)
  end

  def favorite_cars
    @cars = Car.joins(:favorites).where(favorites: { user_id: current_user.id }).order(created_at: :desc)
  end

  # GET /cars/1 or /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars or /cars.json
  def create
    @car = current_user.cars.build(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to car_url(@car), notice: "Car was successfully created." }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1 or /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to car_url(@car), notice: "Car was successfully updated." }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1 or /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy!

    redirect_to root_path
  end

  def search
    if params[:query].present?
      @cars = Car.where('brand LIKE ? OR model LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
                 .order(created_at: :desc)
    else
      @cars = Car.all.order(created_at: :desc)
    end
  end

  def my_search
    @cars = Car.where(user_id: current_user.id)
    if params[:query].present?
      @cars = @cars.where('brand LIKE ? OR model LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    else
      @cars = Car.where(user_id: current_user.id)
    end

    @cars = @cars.order(created_at: :desc)
    render :search
  end


  def liked_search
    @cars = Car.joins(:likes).where(likes: { user_id: current_user.id })

    if params[:query].present?
      @cars = @cars.where('brand LIKE ? OR model LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    end

    @cars = @cars.order(created_at: :desc)
    render :search
  end

  def favorite_search
    @cars = Car.joins(:favorites).where(favorites: { user_id: current_user.id })

    if params[:query].present?
      @cars = @cars.where('brand LIKE ? OR model LIKE ?', "%#{params[:query]}%", "%#{params[:query]}%")
    end

    @cars = @cars.order(created_at: :desc)
    render :search
  end

  def favorite
    car = Car.find(params[:id])
    current_user.favorites.create(car: car)
    respond_to do |format|
      format.html { redirect_to car, notice: 'Car was favorited.' }
      format.js   # Renders favorite.js.erb
      format.turbo_stream
    end
  end

  def unfavorite
    car = Car.find(params[:id])
    favorite = current_user.favorites.find_by(car: car)
    favorite.destroy if favorite
    respond_to do |format|
      format.html { redirect_to car, notice: 'Car was unfavorited.' }
      format.js   # Renders unfavorite.js.erb
      format.turbo_stream
    end
  end

  def models
    make = params[:make]
    models_response = VpicApiService.get_models(make)
    models = models_response['Results']
    render json: models
  end

  private

  def set_car
    @car = Car.find(params[:id])
  end

  def car_params
    params.require(:car).permit(:brand, :model, :likes_count, :image)
  end

  def authorize_user!
    unless @car.user == current_user
      redirect_to root_path, alert: 'You are not authorized to perform this action.'
    end
  end

  def load_makes
    makes_response = VpicApiService.get_makes
    @makes = makes_response['Results'].map { |make| [make['Make_Name'], make['Make_Name']] }
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @cars = Car.all
    @car = Car.new
  end

  def account
  end

  def collection
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_car.html.erb
<div id="<%= dom_id car %>">
  <p>
    <strong>Brand:</strong>
    <%= car.brand %>
  </p>

  <p>
    <strong>Model:</strong>
    <%= car.model %>
  </p>

  <p>
    <strong>Likes:</strong>
    <%= car.likes %>
  </p>

</div>

app/views/cars/_form.html.erb
<div id='form-body'>
  <h1>Car</h1>
  <%= form_with(model: car, local: true, html: { class: 'form' }) do |form| %>
    <% if car.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>
        <ul>
          <% car.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= form.label :brand, 'Brand', class: 'form__label' %>
      <%= form.select :brand, @makes, { include_blank: true }, { id: 'car_brand', class: 'form__input' } %>
    </div>

    <div class="field">
      <%= form.label :model, 'Model', class: 'form__label' %>
      <%= form.select :model, [], { include_blank: true }, { id: 'car_model', class: 'form__input' } %>
    </div>

    <br/>
    <br/>

    <div class="field">
      <%= form.label :image, 'Image', class: 'form__label' %>
      <%= form.file_field :image, class: 'form__input' %>
    </div>

    <div class="actions">
      <%= form.submit 'Add', class: 'form__input' %>
    </div>
  <% end %>
  <br>
</div>

<script>
  document.addEventListener("DOMContentLoaded", function() {
    const brandSelect = document.getElementById("car_brand");
    const modelSelect = document.getElementById("car_model");

    brandSelect.addEventListener("change", function() {
      const brand = brandSelect.value;
      console.log(`Selected brand: ${brand}`); // Debugging-Ausgabe
      fetch(`/cars/models?make=${brand}`)
        .then(response => {
          console.log('Fetch response:', response); // Debugging-Ausgabe
          return response.json();
        })
        .then(data => {
          console.log('Models data:', data); // Debugging-Ausgabe
          while (modelSelect.firstChild) {
            modelSelect.removeChild(modelSelect.firstChild);
          }
          data.forEach(model => {
            const option = document.createElement("option");
            option.value = model.Model_Name;
            option.textContent = model.Model_Name;
            modelSelect.appendChild(option);
          });
        })
        .catch(error => {
          console.error('Error fetching models:', error); // Debugging-Ausgabe
        });
    });
  });
</script>

app/views/cars/_my_car.html.erb
<div class="card-container" data-name="<%= car.brand.downcase %>">
  <% if car.image.attached? %>
    <%= image_tag car.image, class: 'car-pic', alt: car.brand %>
  <% else %>
    <%= image_tag 'icons/image.svg', class: 'car-pic', alt: 'default' %>
  <% end %>
  <div class="card-content">
    <h6 class="title-h6"><%= car.brand %> <%= car.model %></h6>
    <div class="bottom-actions">
      <% if car.user == current_user %>
        <%= button_to car_path(car), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-btn' do %>
          <%= image_tag 'icons/trash.svg', class: 'trash-icon' %>
        <% end %>
        <%= link_to edit_car_path(car), class: 'like-btn' do %>
          <%= image_tag 'icons/edit.svg', class: 'like-icon' %>
        <% end %>
      <% end %>
      
      <div id="like_button_<%= car.id %>">
        <% if current_user %>
          <% if car.liked_by?(current_user) %> 
            <%= link_to car_like_path(car), method: :patch, remote: true, class: 'like-btn', data: { turbo: "true" } do %>
              <%= image_tag 'icons/liked.svg', class: 'like-icon' %>
            <% end %>
          <% else %>
            <%= link_to car_like_path(car), method: :patch, remote: true, class: 'like-btn', data: { turbo: "true" } do %>
              <%= image_tag 'icons/not-liked.svg', class: 'like-icon' %>
            <% end %>
          <% end %>
        <% end %>
      </div>

      <div id="likes_count_<%= car.id %>">
        <h1><%= car.likes.count %></h1>
      </div>
         

      <div id="favorite-button-container">
        <% if current_user %>
          <% if current_user.favorites.find_by(car: car) %>
            <%= button_to unfavorite_car_path(car), method: :delete, remote: true, class: 'like-btn', id: 'favorite-button' do %>
              <%= image_tag 'icons/unfavorite.png', class: 'like-icon' %>
            <% end %>
          <% else %>
            <%= button_to favorite_car_path(car), method: :post, remote: true, class: 'like-btn', id: 'favorite-button' do %>
              <%= image_tag 'icons/favorite.svg', class: 'like-icon' %>
            <% end %>
          <% end %>
        <% end %>
      </div>
      
      <%= link_to 'Download', rails_blob_path(car.image, disposition: "attachment"), class: 'download-png-btn' %>
    </div>
  </div>
</div>

app/views/cars/collection.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>My Collections</h1>
  <br/>
  <h2><%= link_to 'My Cars', my_cars_cars_path, class: 'download-png-btn' %></h2>
  <br/>
  <h2><%= link_to 'My liked Cars', liked_cars_cars_path, class: 'download-png-btn' %></h2>
  <br/>
  <h2><%= link_to 'My favorite Cars', favorite_cars_cars_path, class: 'download-png-btn' %></h2>

  <br/>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'script' %>
</body>
</html>

app/views/cars/edit.html.erb
<head>
  <%= stylesheet_link_tag 'form', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>

<h1>Edit Post</h1>

<%= render "form", car: @car %>

<br>

<div>
  <%= link_to "Show this car", @car %> |
</div>

app/views/cars/favorite_cars.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>My favorite Cars</h1>

    <div class="search-box-container">
    <div class="search-box">
      <i class="bx bx-search"></i>
      <%= form_with url: favorite_search_cars_path, method: :get, local: true do |form| %>
        <%= form.text_field :query, placeholder: "Search in favorite cars", value: params[:query] %>
    <% end %>
    </div>
    </div>

  <div class="outer-container">
    <div class="inner-container" id="my-cars">
      <% if @cars.present? %>
        <% @cars.each do |car| %>
          <%= render partial: 'my_car', locals: { car: car } %>
        <% end %>
      <% else %>
        <p>No cars found.</p>
      <% end %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'script' %>
</body>
</html>

app/views/cars/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Cars</h1>

<div id="cars">
  <% @cars.each do |car| %>
    <%= render car %>
    <p>
      <%= link_to "Show this car", car %>
    </p>
  <% end %>
</div>

<%= link_to "New car", new_car_path %>

app/views/cars/liked_cars.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>My liked Cars</h1>

    <div class="search-box-container">
    <div class="search-box">
      <i class="bx bx-search"></i>
      <%= form_with url: liked_search_cars_path, method: :get, local: true do |form| %>
        <%= form.text_field :query, placeholder: "Search in liked cars", value: params[:query] %>
    <% end %>
    </div>
    </div>

  <div class="outer-container">
    <div class="inner-container" id="my-cars">
      <% if @cars.present? %>
        <% @cars.each do |car| %>
          <%= render partial: 'my_car', locals: { car: car } %>
        <% end %>
      <% else %>
        <p>No cars found.</p>
      <% end %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'script' %>
</body>
</html>

app/views/cars/my_cars.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>My Cars</h1>

  <div class="outer-container">
    <div class="inner-container" id="my-cars">
      <% if @cars.present? %>
        <% @cars.each do |car| %>
          <%= render partial: 'my_car', locals: { car: car } %>
        <% end %>
      <% else %>
        <p>No cars found.</p>
      <% end %>
    </div>
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'script' %>
</body>
</html>

app/views/cars/new.html.erb
<%= stylesheet_link_tag 'form', media: 'all' %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= render "form", car: @car %>

app/views/cars/search.html.erb
  <head>
    <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
    </head>

<h1>Search Results</h1>

<div class="outer-container">
      <div class="inner-container" id="add-card">
        <% @cars.each do |car| %>
          <div class="card-container" data-name="<%= car.brand.downcase %>">
            <% if car.image.attached? %>
              <%= image_tag car.image, class: 'car-pic', alt: car.brand %>
            <% else %>
              <%= image_tag 'icons/image.svg', class: 'car-pic', alt: 'default' %>
            <% end %>
            <div class="card-content">
              <h6 class="title-h6"><%= car.brand %> <%= car.model %></h6>
              <div class="bottom-actions">
                <%= button_to car_path(car), method: :delete, data: { confirm: 'Are you sure?' }, class: 'delete-btn' do %>
                  <%= image_tag 'icons/trash.svg', class: 'trash-icon' %>
                <% end %>
                <%= button_to car_like_path(car), method: :patch, class: 'like-btn', form_class: 'like-form' do %>
                  <%= image_tag car.liked_by?(current_user) ? 'icons/liked.svg' : 'icons/not-liked.svg', class: 'like-icon' %>
                <% end %>
                <h1><%= car.likes_count %></h1>
                <%= link_to 'Download (PNG)', rails_blob_path(car.image, disposition: "attachment"), class: 'download-png-btn' %>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>

app/views/cars/show.html.erb
<p>
  <strong>Brand:</strong>
  <%= @car.brand %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @car.likes %>
</p>

<p>
  <strong>Image:</strong>
  <%= image_tag @car.image if @car.image.attached? %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>

app/views/cars/update.turbo_stream.erb
<turbo-stream action="replace" target="likes_count_<%= @car.id %>">
  <template>
    <h1 id="likes_count_<%= @car.id %>"><%= @car.likes.count %></h1>
  </template>
</turbo-stream>

<turbo-stream action="replace" target="like_button_<%= @car.id %>">
  <template>
    <% if @car.liked_by?(current_user) %>
      <%= link_to car_like_path(@car), method: :patch, remote: true, class: 'like-btn', data: { turbo: "true" }, id: "like_button_<%= @car.id %>" do %>
        <%= image_tag 'icons/liked.svg', class: 'like-icon' %>
      <% end %>
    <% else %>
      <%= link_to car_like_path(@car), method: :patch, remote: true, class: 'like-btn', data: { turbo: "true" }, id: "like_button_<%= @car.id %>" do %>
        <%= image_tag 'icons/not-liked.svg', class: 'like-icon' %>
      <% end %>
    <% end %>
  </template>
</turbo-stream>

app/views/home/_footer.erb
<%= stylesheet_link_tag 'application', media: 'all' %>

 <div class="bottom-right-element">
    <%= link_to "https://github.com/EricLuec/ImageGallery", target: "_blank" do %>
        <%= image_tag "icons/github.svg", class: "icon" %>
    <% end %>
  </div>

app/views/home/_header.erb
<%= stylesheet_link_tag "header", "data-turbo-track": "reload" %>
<header id="header">
  <nav class="links" style="--items: 5;">
    <%= link_to 'Feed', root_path %>
    <%= link_to 'Collection', collection_cars_path %>
    <% if user_signed_in? %>
    <%= link_to 'Account', account_path  %>
    <% else %>
    <%= link_to 'Sign in', new_user_session_path %>
    <% end %>
    <%= link_to 'About', about_path  %>
    <a href="#">Link 5</a>
    <span class="line"></span>
  </nav>
</header>

app/views/home/about.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body id='about'>

<h1>About this project</h1>

</body>
</html>

app/views/home/account.html.erb
<head>
<%= stylesheet_link_tag "form", "data-turbo-track": "reload" %>  
</head>
<div id='form-body'>
<h1>Welcome Home, <%= current_user.email %></h1>
<%= link_to 'Sign out', destroy_user_session_path, class:'link' %>

</div>

app/views/home/index.html.erb
<head>
  <%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'script.js', 'data-turbolinks-track': 'reload' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="navbar">
    <!-- Navigation bar content -->
  </div>

  <div class="search-box-container">
    <div class="search-box">
      <i class="bx bx-search"></i>
      <%= form_with url: search_cars_path, method: :get, local: true do |form| %>
        <%= form.text_field :query, placeholder: "Search a car", value: params[:query] %>

      <% end %>
    </div>
    <%= link_to new_car_path do %>
      <%= image_tag 'icons/add-car.svg', class: 'add-car-icon' %>
    <% end %>
  </div>

  <div class="outer-container">
    <div class="inner-container" id="add-card">
      <% @cars.each do |car| %>
        <%= render partial: 'cars/my_car', locals: { car: car } %>
      <% end %>
    </div>
  </div>

  <div id="modal" class="modal">
    <span class="close">&times;</span>
    <img class="modal-content" id="modal-img" />
  </div>

  <%= javascript_include_tag 'application' %>
  <%= javascript_include_tag 'script' %>
</body> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ImageGallery</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  </head>

  <body>
    <%= render 'home/header' %>
    <p class="alert"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
    <%= render 'home/footer'%>
  </body>
</html>

app/views/layouts/collection.html.erb
<head>
<%= stylesheet_link_tag 'index', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_link_tag 'application', media: 'all' %>
<%= csrf_meta_tags %>
</head>
<body>
    <div class="search-box-container">
        <div class="search-box">
            <i class="bx bx-search"></i>
            <input type="text" placeholder="Search a car" />
        </div>
    </div>
    <%= javascript_include_tag 'script' %>
  </body>
</html>